package main

import (
	"fmt"
	"log"
	"mapreduce"
	"os"
	"strconv"
	"unicode"
)

//
// The map function is called once for each file of input. The first
// argument is the name of the input file, and the second is the
// file's complete contents. You should ignore the input file name,
// and look only at the contents argument. The return value is a slice
// of key/value pairs.
//
func mapF(filename string, contents string) []mapreduce.KeyValue {
	// Count words and save word counts in wc
	wc := make(map[string]int)
	runes := []rune(contents)
	wi := -1	// Index of the start of a new letter
	for i, c := range runes {
		if unicode.IsLetter(c) {
			if wi < 0 {
				wi = i
			}
		} else if wi >= 0 {
			word := string(runes[wi:i])
			if _, ok := wc[word]; ok == true {
				wc[word] += 1
			} else {
				wc[word] = 1
			}
			wi = -1
		}
	}
	// Convert wc to a slice of KeyValue items
	var results []mapreduce.KeyValue
	for key, value := range wc {
		var kv mapreduce.KeyValue
		kv.Key = key
		kv.Value = strconv.Itoa(value)
		results = append(results, kv)
	}
	// Return results
	return results
}

//
// The reduce function is called once for each key generated by the
// map tasks, with a list of all the values created for that key by
// any map task.
//
func reduceF(key string, values []string) string {
	sum := 0
	for _, val := range values {
		intval, err := strconv.Atoi(val)
		if err != nil {
			log.Fatal("reduceF: ", err)
		}
		sum += intval
	}
	return strconv.Itoa(sum)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100, nil)
	}
}
